# Site info
title: colinswaney
description: >- # this means to ignore newlines until "baseurl:"
  A research and development blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http:://github.com/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: cswaney

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax # gs-pages
  syntax_highlighter: rouge # gs-pages
theme: minima
plugins:
  - jekyll-feed
